#!/usr/bin/env bash

sudo apt update --yes && \
sudo apt upgrade --yes && \
sudo apt install software-properties-common --yes && \
sudo apt install git --yes && \
sudo apt install build-essential --yes && \
sudo apt install curl --yes && \
sudo apt-add-repository --yes --update ppa:ansible/ansible && \
sudo apt install ansible --yes && \
sudo apt install nodejs --yes \
