#!/usr/bin/env bash

sudo apt update --yes && \
sudo apt upgrade --yes && \
sudo apt install software-properties-common --yes && \
sudo apt install git --yes && \
sudo apt install build-essential --yes && \
sudo apt install curl --yes && \
sudo apt-add-repository --yes --update ppa:ansible/ansible && \
sudo apt install ansible --yes && \
#sudo apt install nodejs --yes && \
#sudo apt install npm --yes && \
sudo apt install tmux --yes && \
sudo apt install ripgrep --yes && \
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
