- hosts: localhost
  vars:
    home: "{{ home }}"
    ssh_dir: "./.ssh/"
    config: "/usr/bin/git --git-dir={{ home }}/.cfg/ --work-tree={{ home }}"
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/languages.yml
    - include: tasks/zsh.yml
    - include: tasks/tmux.yml
