- hosts: localhost
  vars:
    home: "{{ home }}"
    ssh_dir: "./.ssh/"
    config: "/usr/bin/git --git-dir={{ home }}/.cfg/ --work-tree={{ home }}"
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/languages.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/os.yml
    - import_tasks: tasks/gh.yml
    - import_tasks: tasks/postman.yml
    - import_tasks: tasks/misc.yml
