- hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    ssh_dir: "./.ssh"
  pre_tasks:
    - name: Update Aptitude
      become: true
      apt:
        update_cache: true
        upgrade: yes
      tags:
        - ssh
        - dotfiles
        - zsh
        - tmux
        - neovim
        - node
        - lsp
        - rust
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nerdfonts.yml
    - include: tasks/zsh.yml
    - include: tasks/tmux.yml
    - include: tasks/neovim.yml
    - include: tasks/node.yml
    - include: tasks/rust.yml
    - include: tasks/lsp.yml
