- hosts: localhost
  vars:
    home: "{{ home }}"
    ssh_dir: "./.ssh/"
    config: "/usr/bin/git --git-dir={{ home }}/.cfg/ --work-tree={{ home }}"
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/languages.yml
    - include: tasks/zsh.yml

# OLD STUFF: 
#- hosts: localhost
  #become: yes
  #become_user: lorenzo
  #vars:
    #user: "{{ lookup('env', 'USER') }}"
    #home: "{{ lookup('env', 'HOME') }}"
    #ssh_dir: "./.ssh"
    #config: "/usr/bin/git --git-dir={{ lookup('env', 'HOME') }}/.cfg/ --work-tree={{ lookup('env', 'HOME') }}"
  #vars_prompt:
    #- name: "password"
      #prompt: Enter password
      #private: yes
  #tasks:
    #- include: tasks/debug.yml
    #- include: tasks/ssh.yml
    #- include: tasks/dotfiles.yml
    #- include: tasks/nerdfonts.yml
    #- include: tasks/tmux.yml
    #- include: tasks/zsh.yml
    #- include: tasks/neovim.yml
    #- include: tasks/lsp.yml
