- hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    ssh_dir: "./.ssh"
    config: "/usr/bin/git --git-dir={{ lookup('env', 'HOME') }}/.cfg/ --work-tree={{ lookup('env', 'HOME') }}"
  tasks:
    - include: tasks/debug.yml
    - include: tasks/ssh.yml
    - include: tasks/node.yml
    - include: tasks/rust.yml
    - include: tasks/dotfiles.yml
    - include: tasks/nerdfonts.yml
    - include: tasks/tmux.yml
    - include: tasks/zsh.yml
    - include: tasks/neovim.yml
    - include: tasks/lsp.yml
