- name: Install Docker dependencies
  tags: docker
  become: true
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker GPG key
  tags: docker
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  tags: docker
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker
  tags: docker
  become: true
  apt:
    name: docker-ce
    state: present

- name: Download Docker Compose
  tags: docker
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Set executable permissions for Docker Compose binary
  tags: docker
  become: true
  shell: chmod a+x /usr/local/bin/docker-compose
