- name: Install Stow
  become: true
  apt:
    name: stow
  tags:
    - dotfiles
    - essentials

- name: Clone dotfiles
  git:
    repo: git@github.com:lorenzolfm/.dotfiles.git
    dest: "{{ home }}/.dotfiles"
    key_file: "{{ home }}/.ssh/id_rsa"
  tags:
    - dotfiles
    - essentials

- name: Stow dotfiles
  command:
    cmd: stow .
    chdir: "{{ home }}/.dotfiles"
  tags:
    - dotfiles
    - essentials

- name: Set the correct permissions for configs
  file:
    path: "{{ home }}/{{ item.path }}"
    mode: "{{ item.mode }}"
  tags:
    - dotfiles
    - essentials
  loop:
    - { path: '.config/nvim', mode: '0775' }
    - { path: '.config/i3', mode: '0775' }
    - { path: '.config/i3status', mode: '0775' }
    - { path: '.config/picom', mode: '0775' }
    - { path: '.config/polybar', mode: '0775' }
    - { path: '.config/rofi', mode: '0775' }
    - { path: '.config/spaceship.zsh', mode: '0664' }
    - { path: '.config/theme', mode: '0775' }
    - { path: '.ssh/config', mode: '0777' }
    - { path: '.aliases', mode: '0777' }
    - { path: '.gitconfig', mode: '0777' }
    - { path: '.tmux.conf', mode: '0664' }
    - { path: '.zshenv', mode: '0664' }
    - { path: '.zshrc', mode: '0664' }
