- name: Ignore .cfg folder to avoid recursion problems with dotfiles
  shell: echo ".cfg" >> {{ home }}/.gitignore
  tags:
    - dotfiles

- name: Clone dotfiles into a bare repository
  shell: git clone --bare git@github.com:lorenzolfm/dotfiles.git {{ home }}/.cfg
  tags:
    - dotfiles

- name: Checkout the content from the bare repo to home
  shell: "{{ config }} checkout"
  tags:
    - dotfiles

- name: Set the flag showUntrackedFiles to no on this specific (local) repo
  shell:
    "{{ config }} config --local status.showUntrackedFiles no"
  tags:
    - dotfiles
