- name: Ignore .cfg folder to avoid wierd recursion problems with the dotfiles
  shell: echo ".cfg" >> {{ home }}/.gitignore
  tags:
    - dotfiles
    - essentials

- name: Clone dotfiles into a bare repository
  git:
    repo: git@github.com:lorenzolfm/dotfiles.git
    dest: "{{ home }}/.cfg"
    key_file: "{{ home }}/.ssh/id_rsa"
    bare: true
  tags:
    - dotfiles
    - essentials

- name: Checkout the content from the bare repo to home
  shell: "{{ config }} checkout"
  tags:
    - dotfiles
    - essentials

- name: Set the flag showUntrackedFiles to no on this specific (local) repo
  shell:
    "{{ config }} config --local status.showUntrackedFiles no"
  tags:
    - dotfiles
    - essentials

- name: Set the correct permissions for configs
  file:
    path: "{{ home }}/{{ item.path }}"
    mode: "{{ item.mode }}"
  tags:
    - dotfiles
    - essentials
  loop:
    - { path: '.gitignore', mode: '0664' }
    - { path: '.cfg', mode: '0775' }
    - { path: '.config/nvim', mode: '0775' }
    - { path: '.ssh/config', mode: '0604' }
    - { path: '.aliases', mode: '0664' }
    - { path: '.gitconfig', mode: '0664' }
    - { path: '.tmux.conf', mode: '0664' }
    - { path: '.zshenv', mode: '0664' }
    - { path: '.zshrc', mode: '0664' }
