- name: Download Installer
  tags: languages
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0755
    force: 'yes'

- name: Install rust/cargo
  tags: languages
  shell: /tmp/sh.rustup.rs -y

- name: Install nodejs and npm
  tags: languages
  become: true
  apt:
    name: ["nodejs", "npm"]

- name: Install nvm
  tags: languages
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash"

- name: Change permissions for nvm
  tags: languages
  file:
    path: "{{ home }}/.nvm"
    mode: 0775
