- name: Install KeePassXc
  become: true
  apt:
    name: keepassxc
  tags: 
    - keepassxc
    - misc

- name: Download password repo
  git:
    repo: git@github.com:lorenzolfm/pwds.git
    dest: "{{ home }}/pwds"
    key_file: "{{ home }}/.ssh/id_rsa"
  tags: 
    - keepassxc
    - misc

- name: Change permissions for passwords folder
  file:
    path: "{{ home }}/pwds"
    mode: 0775
  tags: 
    - keepassxc
    - misc

- name: Add Spotify's GPG key
  shell: curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
  tags: 
    - spotify
    - misc

- name: Add Spotify repository key and source
  become: true
  shell: |
    curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
    echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
  tags:
    - spotify
    - misc

- name: Install Spotify client
  become: true
  apt:
    name: spotify-client
    update_cache: yes
  tags:
    - spotify
    - misc

- name: Change permissions for spotify
  become: true
  file:
    path: "/usr/bin/spotify"
    mode: 0777
  tags: 
    - spotify
    - misc

- name: Download Brave keyring
  become: true
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
  tags:
    - brave
    - misc

- name: Add Brave repository to sources list
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/brave-browser-release.list
    line: 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
    create: true
    state: present
  tags:
    - brave
    - misc

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  tags:
    - brave
    - misc

- name: Install Brave browser
  become: true
  apt:
    name: brave-browser
    state: present
  tags:
    - brave
    - misc

- name: Download Slack
  get_url:
    url: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.19.2-amd64.deb
    dest: /tmp/slack.deb
  tags:
    - slack
    - misc

- name: Remove Any previous slacks
  become: true
  apt:
    name: slack-desktop
    state: absent
  tags:
    - slack
    - misc

- name: Install Slack .deb package
  become: true
  apt:
    deb: /tmp/slack.deb
  tags:
    - slack
    - misc

- name: Download Discord .deb package
  become: true
  get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb
  tags:
    - discord
    - misc

- name: Install Discord
  become: true
  apt:
    deb: /tmp/discord.deb
  tags:
    - discord
    - misc

- name: Install Telegram
  become: true
  apt:
    name: telegram-desktop
  tags:
    - telegram
    - misc

- name: Download nerdfonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts
    dest: "{{ home }}/nerd-fonts"
  tags: 
    - nerdfonts
    - misc

- name: Install fonts
  shell: "{{ home }}/./nerd-fonts/install.sh"
  tags:
    - nerdfonts
    - misc

- name: Remove nerd-fonts repo
  shell: "rm -rf {{ home }}/nerd-fonts"
  tags:
    - nerdfonts
    - misc

- name: Change permissions for fonts
  file:
    path: "{{ home }}/.local/share/fonts/NerdFonts"
    mode: 0775
  tags:
    - nerdfonts
    - misc

- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0755"
  tags:
    - bitwarden
    - misc

- name: Get Bitwarden latest release URL
  uri:
    url: https://api.github.com/repos/bitwarden/desktop/releases/latest
    return_content: yes
    headers:
      Accept: "application/vnd.github+json"
  register: bitwarden_release
  tags:
    - bitwarden
    - misc

- name: Download Bitwarden AppImage
  get_url:
    url: "{{ bitwarden_release.json.assets | selectattr('name', 'contains', 'AppImage') | map(attribute='browser_download_url') | first }}"
    dest: "{{ home }}/.local/bin/bitwarden.AppImage"
    mode: "0775"
  tags:
    - bitwarden
    - misc

- name: Download Sparrow .deb file
  become: true
  get_url:
    url: https://github.com/sparrowwallet/sparrow/releases/download/1.7.4/sparrow_1.7.4-1_amd64.deb
    dest: /tmp/sparrow_1.7.4-1_amd64.deb
  tags:
    - sparrow
    - misc

- name: Install Sparrow from the .deb file
  become: true
  apt:
    deb: /tmp/sparrow_1.7.4-1_amd64.deb
  tags:
    - sparrow
    - misc

- name: Remove downloaded Sparrow .deb file
  become: true
  file:
    path: /tmp/sparrow_1.7.4-1_amd64.deb
    state: absent
  tags:
    - sparrow
    - misc

#- name: Verify Sparrow signature
  #shell: "gpg --verify sparrow-1.7.3-manifest.txt.asc"
  #args:
    #chdir: /path/to/sparrow/directory
  #tags:
    #- sparrow
    #- misc

#- name: Check SHA256 checksum
  #shell: "sha256sum --check sparrow-1.7.3-manifest.txt --ignore-missing"
  #args:
    #chdir: /path/to/sparrow/directory
  #tags:
    #- sparrow
    #- misc

#- name: Download and install Sparrow
  #get_url:
    #url: https://github.com/sparrowwallet/sparrow/releases/download/1.7.3/sparrow_1.7.3-1_amd64.deb
    #dest: /tmp/sparrow.deb
  #become: true
  #tags:
    #- sparrow
    #- misc

#- name: Install Sparrow package
  #apt:
    #deb: /tmp/sparrow.deb
  #become: true
  #tags:
    #- sparrow
    #- misc
    #
