- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - keepassxc
    - telegram-desktop
    - gnome-tweaks
  tags:
    - misc

- name: Get Bitwarden latest release URL
  uri:
    url: https://api.github.com/repos/bitwarden/desktop/releases/latest
    return_content: yes
    headers:
      Accept: "application/vnd.github+json"
  register: bitwarden_release
  tags:
    - bitwarden
    - misc

- name: Ensure ~/.local/bin directory exists
  file:
    path: "{{ home }}/.local/bin"
    state: directory
    mode: "0755"
  tags:
    - bitwarden
    - misc

- name: Check if DISPLAY environment variable is set
  shell: echo $DISPLAY
  register: display_env_var
  tags:
    - sparrow
    - misc

- name: Download files
  become: true
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
      mode: '0644'
    - url: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.19.2-amd64.deb
      dest: /tmp/slack.deb
    - url: https://discord.com/api/download?platform=linux&format=deb
      dest: /tmp/discord.deb
    - url: "{{ bitwarden_release.json.assets | selectattr('name', 'contains', 'AppImage') | map(attribute='browser_download_url') | first }}"
      dest: "{{ home }}/.local/bin/bitwarden.AppImage"
      mode: "0775"
    - url: https://github.com/sparrowwallet/sparrow/releases/download/1.7.4/sparrow_1.7.4-1_amd64.deb
      dest: /tmp/sparrow_1.7.4-1_amd64.deb
  when: display_env_var.stdout != "" or item.url != 'https://github.com/sparrowwallet/sparrow/releases/download/1.7.4/sparrow_1.7.4-1_amd64.deb'
  tags:
    - misc

- name: Add Spotify's GPG key and repository
  become: true
  shell: |
    curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
    echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
  tags:
    - misc

- name: Remove Any previous slacks
  become: true
  apt:
    name: slack-desktop
    state: absent
  tags:
    - slack
    - misc

- name: Install .deb packages
  become: true
  apt:
    deb: "{{ item }}"
  loop:
    - /tmp/sparrow_1.7.4-1_amd64.deb
    - /tmp/slack.deb
    - /tmp/discord.deb
  loop_control:
    loop_var: item
  when: (display_env_var.stdout != "" and item == "/tmp/sparrow_1.7.4-1_amd64.deb") or (item != "/tmp/sparrow_1.7.4-1_amd64.deb")
  tags:
    - misc

- name: Download repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ home }}/{{ item.dest }}"
    key_file: "{{ item.key_file | default(omit) }}"
  loop:
    - repo: git@github.com:lorenzolfm/pwds.git
      dest: pwds
      key_file: "{{ home }}/.ssh/id_rsa"
    - repo: https://github.com/ryanoasis/nerd-fonts
      dest: nerd-fonts
  tags:
    - misc

- name: Install fonts
  shell: "{{ home }}/./nerd-fonts/install.sh"
  tags:
    - nerdfonts
    - misc

- name: Add Brave repository to sources list
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/brave-browser-release.list
    line: 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
    create: true
    state: present
  tags:
    - brave
    - misc

- name: Install software packages and update apt cache
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - spotify-client
    - brave-browser
  tags:
    - misc
- name: Change permissions
  become: true
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items:
    - path: "/usr/bin/spotify"
      mode: "0777"
    - path: "{{ home }}/.local/share/fonts/NerdFonts"
      mode: "0775"
    - path: "{{ home }}/pwds"
      mode: "0775"
  tags:
    - misc

- name: Remove files and directories
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - path: "{{ home }}/nerd-fonts"
    - path: "/tmp/sparrow_1.7.4-1_amd64.deb"
      condition: display_env_var.stdout != ""
  when: item.condition | default(true)
  tags:
    - misc
