- name: Install NeoVim
  shell: curl -L https://github.com/neovim/neovim/releases/download/v0.8.0/nvim.appimage -O
  tags:
    - neovim

- name: Make it executable
  shell: chmod u+x nvim.appimage
  tags:
    - neovim

- name: Install Vim-Plug
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  tags:
    - neovim

- name: Install Telescope dep ripgrep
  apt: name=ripgrep
  tags:
    - neovim
