- name: Install fd-find, ripgrep, and neovim
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - fd-find
    - ripgrep
  tags:
    - neovim
    - essentials

- name: Create .local/bin directory and symlink fd
  shell:
    cmd: |
      mkdir -p {{ home }}/.local/bin
      ln -s $(which fdfind) {{ home }}/.local/bin/fd
  tags:
    - neovim
    - essentials

- name: Install NeoVim and make it executable
  shell:
    cmd: |
      curl -L https://github.com/neovim/neovim/releases/download/v0.9.0/nvim.appimage -o {{ home }}/nvim.appimage
      chmod u+x {{ home }}/nvim.appimage
  tags:
    - neovim
    - essentials

- name: Install Packer Sync
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
    version: HEAD
  tags:
    - neovim
    - essentials

- name: Set permissions for nvim.appimage and packer
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ home }}/nvim.appimage", mode: "0775" }
    - { path: "{{ home }}/.local/share/nvim/site/pack/packer/start/packer.nvim", mode: "0775" }
  loop_control:
    label: "{{ item.path }}"
  tags:
    - neovim
    - essentials
