- name: Download Nerdfonts
  shell: "git clone https://github.com/ryanoasis/nerd-fonts {{ home }}/nerd-fonts"
  tags:
    - nerdfonts

- name: Install all fonts
  shell: "{{ home }}/./nerd-fonts/install.sh"
  tags:
    - nerdfonts

- name: Remove repo
  shell: "rm -rf {{ home }}/nerd-fonts"
  tags:
    - nerdfonts
