- name: Ensure .ssh directory exists
  file:
    dest: "{{ home }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - ssh
    - essentials

- name: Copy personal ssh private key
  copy:
    src: "{{ ssh_dir }}/id_rsa"
    dest: "{{ home }}/.ssh/id_rsa"
    mode: 0600
  tags:
    - ssh
    - essentials

- name: Copy personal ssh public key
  copy:
    src: "{{ ssh_dir }}/id_rsa.pub"
    dest: "{{ home }}/.ssh/id_rsa.pub"
    mode: 0644
  tags:
    - ssh
    - essentials

- name: Copy known hosts
  copy:
    src: "{{ ssh_dir }}/known_hosts"
    dest: "{{ home }}/.ssh/known_hosts"
    mode: 0644
  tags:
    - ssh
    - essentials
