- name: Ensure .ssh directory exists
  file:
    dest: "{{ home }}/.ssh"
    mode: 0700
    state: directory

- name: Copy personal ssh private key
  copy:
    src: "{{ ssh_dir }}/id_rsa"
    dest: "{{ home }}/.ssh/id_rsa"
    mode: 0600

- name: Copy personal ssh public key
  copy:
    src: "{{ ssh_dir }}/id_rsa.pub"
    dest: "{{ home }}/.ssh/id_rsa.pub"
    mode: 0644
  tags:
    - ssh
