- name: Ensure .ssh directory exists
  file:
    dest: "{{ home }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Copy personal ssh private key
  copy:
    src: "{{ ssh_dir }}/id_rsa"
    dest: "{{ home }}/.ssh/id_rsa"
  tags:
    - ssh

- name: Copy personal ssh public key
  copy:
    src: "{{ ssh_dir }}/id_rsa.pub"
    dest: "{{ home }}/.ssh/id_rsa.pub"
  tags:
    - ssh

- name: Copy work ssh private key
  copy:
    src: "{{ ssh_dir }}/id_rsa_work"
    dest: "{{ home }}/.ssh/id_rsa_work"
  tags:
    - ssh

- name: Copy work ssh public key
  copy:
    src: "{{ ssh_dir }}/id_rsa_work.pub"
    dest: "{{ home }}/.ssh/id_rsa_work.pub"
  tags:
    - ssh
