- name: Install zsh
  become: true
  apt:
    name: zsh
  tags:
    - zsh
    - essentials

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - zsh
    - essentials

- name: Check if Oh-My-Zsh already exists
  stat:
    path: "{{ home }}/.oh-my-zsh"
  register: omz_exists
  tags:
    - zsh
    - essentials

- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not omz_exists.stat.exists
  tags:
    - zsh
    - essentials

- name: Check if zshrc.pre-oh-my-zsh exists
  stat:
    path: "{{ home }}/.zshrc.pre-oh-my-zsh"
  register: old_zshrc_exists
  tags:
    - zsh
    - essentials

- name: Replace .zshrc with .zshrc.pre-oh-my-zsh
  shell: "rm -rf {{ home }}/.zshrc && mv {{ home }}/.zshrc.pre-oh-my-zsh {{ home }}/.zshrc"
  when: old_zshrc_exists.stat.exists
  tags:
    - zsh
    - essentials

- name: Install git repositories and set permissions
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  tags:
    - zsh
    - essentials
  loop:
    - repo: https://github.com/unixorn/fzf-zsh-plugin.git
      dest: "{{ home }}/.oh-my-zsh/plugins/fzf-zsh-plugin"
    - repo: https://github.com/agkozak/zsh-z.git
      dest: "{{ home }}/.oh-my-zsh/plugins/zsh-z"
    - repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: git_repos

- name: Set permissions for git repositories
  file:
    path: "{{ item.item.dest }}"
    mode: 0775
  tags:
    - zsh
    - essentials
  loop: "{{ git_repos.results }}"
