- name: Install ZSH
  apt: name=zsh
  tags:
    - zsh

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - zsh

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh

- name: Install Spaceship-theme
  ansible.builtin.git:
    repo: 'https://github.com/spaceship-prompt/spaceship-prompt'
    depth: 1
    dest: '~/.oh-my-zsh/themes/zsh-autosuggestions'
  tags:
    - zsh

- name: Install zsh-z plugin
  ansible.builtin.git:
    repo: 'https://github.com/agkozak/zsh-z.git'
    dest: '~/.oh-my-zsh/plugins/zsh-z'
  tags:
    - zsh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
    - zsh
