- name: Install zsh
  become: true
  tags: zsh
  apt:
    name: zsh

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)

- name: Install Oh-My-Zsh
  tags: zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Check if zshrc.pre-oh-my-zsh exists
  tags: zsh
  stat:
    path: "{{ home }}/.zshrc.pre-oh-my-zsh"
  register: old_zshrc_exists

- name: Replace .zshrc with .zshrc.pre-oh-my-zsh
  tags: zsh
  shell: "rm -rf {{ home }}/.zshrc && mv {{ home }}/.zshrc.pre-oh-my-zsh {{ home }}/.zshrc"
  when: old_zshrc_exists.stat.exists

- name: Install Spaceship theme
  tags: zsh
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "{{ home }}/.oh-my-zsh/custom/themes/spaceship-prompt"

- name: Change permissions for Spaceship theme folder
  tags: zsh
  file:
    path: "{{ home }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    mode: 0775

- name: Symlink spaceship.zsh-theme to oh-my-zsh custom themes directory
  shell: "ln -s {{ home }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme {{ home }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
  tags:
    - zsh

- name: Install zsh-z plugin
  tags: zsh
  git:
    repo: https://github.com/agkozak/zsh-z.git
    dest: "{{ home }}/.oh-my-zsh/plugins/zsh-z" 

- name: Install zsh-autosuggestions
  tags: zsh
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Change permissions for zsh-autosuggestions
  tags: zsh
  file:
    path: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    mode: 0775
