- name: Install ZSH
  apt: name=zsh
  tags:
    - zsh

- name: Change shell to zsh
  expect:
    command: "chsh -s /usr/bin/zsh"
    responses:
      (?i)password: "{{ password }}"
  tags:
    - zsh

- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh

- name: Install Spaceship theme
  shell: "git clone https://github.com/spaceship-prompt/spaceship-prompt.git {{ home }}/.oh-my-zsh/custom/themes/spaceship-prompt"
  tags:
    - zsh

- name: Symlink spaceship.zsh-theme to oh-my-zsh custom themes directory
  shell: "ln -s {{ home }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme {{ home }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
  tags:
    - zsh

- name: Install zsh-z plugin
  shell: "git clone https://github.com/agkozak/zsh-z.git {{ home }}/.oh-my-zsh/plugins/zsh-z"
  tags:
    - zsh

- name: Install zsh-autosuggestions
  shell: "git clone https://github.com/zsh-users/zsh-autosuggestions.git {{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh

- name: Check if zshrc.pre-oh-my-zsh exists
  stat:
    path: "{{ home }}/.zshrc.pre-oh-my-zsh"
  register: old_zshrc_exists
  tags:
    - zsh

- name: Replace .zshrc with .zshrc.pre-oh-my-zsh
  shell: "rm -rf {{ home }}/.zshrc && mv {{ home }}/.zshrc.pre-oh-my-zsh {{ home }}/.zshrc"
  when: old_zshrc_exists.stat.exists
  tags:
    - zsh
